/*
 * File: app/store/AllObjectsStore.js
 * Date: Mon Sep 05 2011 19:04:54 GMT+0300 (FLE Daylight Time)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Borsuko.store.AllObjectsStore', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            autoSync: true,
            storeId: 'AllObjectsStore',
            proxy: {
                type: 'ajax',
                url: './php//ObjView_All.php',
                reader: {
                    type: 'json',
                    root: 'data'
                }
            },
            fields: [
                {
                    type: 'int',
					name: 'ID'
                },
                {
                    name: 'nazva'
                },
                {
                    name: 'prymitka'
                },
                {
                    name: 'telefon'
                },
                {
                    name: 'Variant'
                },
                {
                    name: 'objthemes'
                },
                {
                    name: 'zamovnyk'
                },
                {
                    name: 'Vykonavci'
                },
                {
                    name: 'PIB'
                },
                {
                    name: 'adresa'
                },
                {
                    name: 'PDV'
                },
                {
                    name: 'znyzhka'
                },
                {
                    name: 'Moment_dollar'
                },
                {
                    name: 'Moment_euro'
                },
                {
                    name: 'nomer'
                },
                {
                    name: 'Stan_objektu'
                },
                {
                    name: 'date'
                }
            ]
        }, cfg)]);
    }
});