/*
 * File: app/store/events_statuses.js
 * Date: Mon Sep 05 2011 19:04:54 GMT+0300 (FLE Daylight Time)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Borsuko.store.events_statuses', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'events_statuses',
            proxy: {
                type: 'ajax',
                url: './Json/events_statuses.json',
                reader: {
                    type: 'json',
                    root: 'data'
                }
            },
            fields: [
                { name: 'event_status_id'},
				{ name: 'event_status'}
            ]
        }, cfg)]);
    }
});