/*
 * File: app/store/NariadView_Open.js
 * Date: Mon Sep 05 2011 19:04:54 GMT+0300 (FLE Daylight Time)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Borsuko.store.NariadView_Open', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'NariadView_Open',
            proxy: {
                type: 'ajax',
                url: './php/view_nariady_open.php',
                reader: {
                    type: 'json',
                    root: 'data'
                }
            },
            fields: [
                {
                    type: 'int',
					name: 'ID'
                },
                {
                    name: 'P_kontragent'
                },
                {
                    name: 'S_kontragent'
                },
                {
                    name: 'Prymitka'
                },
                {
                    name: 'Date'
                },
                {
                    name: 'Object'
                }
            ]
        }, cfg)]);
    }
});