/*
 * File: app/store/ordersArchieved.js
 * Date: Mon Sep 05 2011 19:04:54 GMT+0300 (FLE Daylight Time)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Borsuko.store.ordersArchieved', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
	 pageSize: 20,
            autoSync: true,
            storeId: 'ordersArchieved',
            proxy: {
                type: 'ajax',
                url: './php/ordersArchieved.php',
                reader: {
                    type: 'json',
                    root: 'data'
                }
            },
            fields: [
			{ name: 'order_id' },
			{ name: 'date' },
			{ name: 'name1' },
			{ name: 'name2' },
			{ name: 'surname' },
			{ name: 'email' },
			{ name: 'idcard' },
			{ name: 'notes' },
			{ name: 'status' },
			{ name: 'isdeleted' }

            ]
        }, cfg)]);
    }
});