/*
 * File: app/store/SkladStore.js
 * Date: Mon Sep 05 2011 19:04:54 GMT+0300 (FLE Daylight Time)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Borsuko.store.SkladStore', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
			pageSize: 20,
            autoSync: true,
            storeId: 'SkladStore',
            proxy: {
                type: 'ajax',
                url: './php/view_sklad.php',
                reader: {
                    type: 'json',
                    root: 'data'
                }
            },
            fields: [
                {
                    type: 'int',
					name: 'ThemeId'
                },
                {
                    name: 'Type'
                },
                {
                    type: 'int',
					name: 'count'
                },
                {
                    name: 'CategoryId'
                },
                {
                    name: 'CategoryName'
                },
                {
                    name: 'OtrymanoVid'
                },
                {
                    name: 'SubCategoryId'
                },
                {
                    name: 'SubCategoryName'
                },
                {
                    type: 'int',
					name: 'ModelId'
                },
                {
                    name: 'Model'
                },
                {
                    name: 'Vendor'
                },
				{
                    name: 'Prymitka'
                },
                {
                    name: 'Description'
                },
                {
                    name: 'OdVym'
                },
                {
                    name: 'Price',
                    type: 'float'
                },
                {
                    name: 'Time',
                    type: 'float'
                },
                {
                    name: 'Valiuta'
                },
                {
                    name: 'euro'
                },
                {
                    name: 'dollar'
                },
                {
                    name: 'grivna'
                }
            ]
        }, cfg)]);
    }
});