/*
 * File: app/store/store_fond.js
 * Date: Mon Sep 05 2011 19:04:54 GMT+0300 (FLE Daylight Time)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Borsuko.store.store_fond', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
			pageSize: 20,
            autoSync: true,
            storeId: 'store_fond',
            proxy: {
                type: 'ajax',
                url: './php/fond_edit.php',
                reader: {
                    type: 'json',
                    root: 'data'
                }
            },
            fields: [
                {
                    type: 'int',
					name: 'ID'
                },
                {
                    name: 'DateZminaCountu'
                },
                {
                    name: 'Prymitka'
                },
                {
                    //type: 'date',
					name: 'Date'
                },
                {
                    name: 'Type'
                },
                {
                    type: 'int',
					name: 'Count'
                },
                {
                    name: 'Model'
                },
                {
                    name: 'Vendor'
                },
                {
                    name: 'Description'
                },
                {
                    name: 'OdVym'
                },
                {
                    name: 'Price',
                    type: 'float'
                },
                {
                    name: 'Valiuta'
                }
            ]
        }, cfg)]);
    }
});