/*
 * File: app/view/narahuvania_view.js
 * Date: Mon Sep 05 2011 19:04:54 GMT+0300 (FLE Daylight Time)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('Borsuko.view.narahuvania_view', {
    extend: 'Borsuko.view.ui.narahuvania_view',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});