/*
 * File: app/view/ui/add_to_price.js
 * Date: Tue Sep 06 2011 18:19:14 GMT+0300 (FLE Daylight Time)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Borsuko.view.ui.add_to_price', {
    extend: 'Ext.form.Panel',

    autoRender: true,
    autoShow: true,
    frame: true,
    id: 'form',
    itemId: 'form',
    styleHtmlContent: true,
    autoScroll: true,
    maintainFlex: true,
    layout: {
        type: 'auto'
    },
    bodyPadding: 10,
    animCollapse: false,
    collapseFirst: false,
    collapsed: false,
    collapsible: true,
    frameHeader: false,
    title: 'Додати в Прайс',
    titleCollapse: true,
    pollForChanges: true,
    paramsAsHash: true,
    standardSubmit: true,
    trackResetOnLoad: true,

    initComponent: function() {
        var me = this;
        me.items = [
            {
                xtype: 'fieldset',
                frame: true,
                padding: 10,
                width: 852,
				listeners: {
						afterrender: function() {
						Ext.getCmp("count").setValue("1");
							}
						},
                items: [
                    {
                        xtype: 'textfield',
						//anchor:'20%',
                        id: 'count',
                        width: 300,
                        name: 'count',
                        fieldLabel: 'Кількість (для складу)',
                        labelWidth: 150,
                    },
					{
                        xtype: 'combobox', editable: false,
                        id: 'Type',
                        width: 500,
                        name: 'Type',
                        fieldLabel: 'Тип Обладнання',
                        labelWidth: 150,
                        emptyText: 'Вибір...',
                        displayField: 'type',
                        store: 'TypObladnannia_Store',
                        valueField: 'type'
                    },
                    {
                        xtype: 'combobox', editable: false,
                        id: 'Tema',
                        width: 500,
                        name: 'Tema',
                        fieldLabel: 'Тема об`єкту',
                        labelWidth: 150,
                        emptyText: 'Вибір...',
                        displayField: 'ObjectThemesName',
                        store: 'ObjThemesStore',
                        valueField: 'ObjectThemesName'
                    },
                    {
                        xtype: 'combobox', editable: false,
                        id: 'Category',
                        width: 500,
                        fieldLabel: 'Категорія',
                        labelWidth: 150,
                        emptyText: 'Вибір...',
                        displayField: 'CategoryName',
                        store: 'CategoryStore',
                        valueField: 'CategoryName'
                    },
                    {
                        xtype: 'combobox', editable: false,
                        id: 'SubCategory',
                        width: 500,
                        fieldLabel: 'Субкатегорія',
                        labelWidth: 150,
                        emptyText: 'Вибір...',
                        displayField: 'SubCategoryName',
                        store: 'SubCategoryStore',
                        valueField: 'SubCategoryName'
                    },
                    {
                        xtype: 'textfield',
                        id: 'Model',
                        width: 500,
                        name: 'Model',
                        fieldLabel: 'Модель',
                        labelWidth: 150,
                        emptyText: 'Назва моделі'
                    },
                    {
                        xtype: 'textareafield',
                        height: 85,
                        id: 'Description',
                        width: 500,
                        name: 'Description',
                        fieldLabel: 'Опис',
                        labelWidth: 150,
                        emptyText: 'Опис'
                    },
                    {
                        xtype: 'combobox', editable: false,
                        id: 'OdVym',
                        width: 500,
                        name: 'OdVym',
                        fieldLabel: 'Одиниці виміру',
                        labelWidth: 150,
                        emptyText: 'Вибір...',
                        displayField: 'OdVymiru',
                        store: 'store_OdVymiru',
                        valueField: 'OdVymiru'
                    },
                    {
                        xtype: 'textfield',
                        id: 'Vendor',
                        width: 500,
                        name: 'Vendor',
                        fieldLabel: 'Виробник',
                        labelWidth: 150,
                        emptyText: 'Виробник'
                    },
                    {
                        xtype: 'textfield',
                        id: 'Price',
                        width: 500,
                        name: 'Price',
                        fieldLabel: 'Ціна',
                        labelWidth: 150,
                        emptyText: 'Ціна в валюті'
                    },
                    {
                        xtype: 'combobox', editable: false,
                        id: 'Valiuta',
                        width: 500,
                        fieldLabel: 'Валюта',
                        labelWidth: 150,
                        emptyText: 'Вибір...',
                        displayField: 'name',
                        queryMode: 'local',
                        store: 'ValiutaStore',
                        valueField: 'abbr'
                    },
                    {
                        xtype: 'textfield',
                        id: 'Nacinka',
                        width: 500,
                        name: 'Nacinka',
                        fieldLabel: 'Націнка (%)',
                        labelWidth: 150,
                        emptyText: 'Націнка в %'
                    },
                    {
                        xtype: 'textfield',
                        id: 'Time',
                        width: 500,
                        name: 'Time',
                        fieldLabel: 'Час встановлення (хв.)',
                        labelWidth: 150,
                        emptyText: 'Час встановдення (в хвилинах)'
                    }
                ]
            }
        ];
        me.dockedItems = [
            {
                xtype: 'toolbar',
                dock: 'top',
                items: [
                    {
                        xtype: 'button',
                        id: 'add',
                        text: 'Додати в Прайс',
						iconCls: 'add',
						handler : function(){
						AddToPrice()
						}
						
                    },
					{
                        xtype: 'button',
                        id: 'add_sklad',
						iconCls: 'add',
                        text: 'Додати в Прайс та на Склад',
						handler : function(){
						AddToPriceSklad()
						}
					}
                ]
            }
        ];
        me.callParent(arguments);
    }
});

function AddToPriceSklad(){
				
		var str_Type = Ext.getCmp("Type").getValue();
		var str_Tema = Ext.getCmp("Tema").getValue();
		var str_Category = Ext.getCmp("Category").getValue();
		var str_CategoryId = "";
		var str_SubCategory = Ext.getCmp("SubCategory").getValue();
		var str_SubCategoryId = "";
		var str_Model = Ext.getCmp("Model").getValue();
		var str_Description= Ext.getCmp("Description").getValue();
		var str_OdVym = Ext.getCmp("OdVym").getValue();
		var str_Vendor = Ext.getCmp("Vendor").getValue();
		var str_Price = Ext.getCmp("Price").getValue();
		var str_Valiuta = Ext.getCmp("Valiuta").getValue();
		var str_Nacinka = Ext.getCmp("Nacinka").getValue();
		var str_Time = Ext.getCmp("Time").getValue();
		var str_count = Ext.getCmp("count").getValue();
	  
		switch (str_Type)
			{
			case 'монтажні':
				strTable = 'montazh';
				//strTypeID = 2;
				strTypeID = 2;
				break;
			case 'активні': 
				strTable = 'active';
				strTypeID = 1;
				break;
			}  
		  
	//Додавання в Каталог
	Ext.Ajax.request(
	{
		url: './php/insert_to_price-sklad.php',
		params: {
		Type: str_Type ,
		Tema: str_Tema , 
		Category: str_Category ,
		CountOnSklad: str_count,
		CategoryId: str_CategoryId ,
		SubCategory: str_SubCategory ,
		SubCategoryId: str_SubCategoryId ,
		Model: str_Model ,
		Description: str_Description,
		OdVym: str_OdVym ,
		Vendor: str_Vendor ,
		Price: str_Price ,
		Valiuta: str_Valiuta ,
		Nacinka: str_Nacinka ,
		Time: str_Time,
		Table:strTable,
		TypeID:strTypeID
			
		},
		success: function()
		{
			Ext.MessageBox.alert('товар доданий!', 'Товар доданий');
			
		},
		failure: function(response)
		{
			Ext.MessageBox.alert('Помилка', 'Неможливо доступитися до бази даних');
		}
	})
	
					
	}

	function AddToPrice(){
		var str_Type = Ext.getCmp("Type").getValue();
		var str_Tema = Ext.getCmp("Tema").getValue();
		var str_Category = Ext.getCmp("Category").getValue();
		var str_CategoryId = "";
		var str_SubCategory = Ext.getCmp("SubCategory").getValue();
		var str_SubCategoryId = "";
		var str_Model = Ext.getCmp("Model").getValue();
		var str_Description= Ext.getCmp("Description").getValue();
		var str_OdVym = Ext.getCmp("OdVym").getValue();
		var str_Vendor = Ext.getCmp("Vendor").getValue();
		var str_Price = Ext.getCmp("Price").getValue();
		var str_Valiuta = Ext.getCmp("Valiuta").getValue();
		var str_Nacinka = Ext.getCmp("Nacinka").getValue();
		var str_Time = Ext.getCmp("Time").getValue();
	  
		switch (str_Type)
			{
			case 'монтажні':
				strTable = 'montazh';
				strTypeID = 2;
				break;
			case 'активні': 
				strTable = 'active';
				strTypeID = 1;
				break;
			}  
		  
	
	Ext.Ajax.request(
	{
		url: './php/Insert_to_price.php',
		params: {
		Type: str_Type ,
		Tema: str_Tema , 
		Category: str_Category ,
		CategoryId: str_CategoryId ,
		SubCategory: str_SubCategory ,
		SubCategoryId: str_SubCategoryId ,
		Model: str_Model ,
		Description: str_Description,
		OdVym: str_OdVym ,
		Vendor: str_Vendor ,
		Price: str_Price ,
		Valiuta: str_Valiuta ,
		Nacinka: str_Nacinka ,
		Time: str_Time,
		Table:strTable,
		TypeID:strTypeID
			
		},
		success: function()
		{
			Ext.MessageBox.alert('товар доданий!', 'Товар доданий');
			Ext.getCmp("Type").reset();
			Ext.getCmp("Tema").reset();
			Ext.getCmp("Category").reset();
			Ext.getCmp("SubCategory").reset();
			Ext.getCmp("Model").reset();
			Ext.getCmp("Description").reset();
			Ext.getCmp("OdVym").reset();
			Ext.getCmp("Vendor").reset();
			Ext.getCmp("Price").reset();
			Ext.getCmp("Valiuta").reset();
			Ext.getCmp("Nacinka").reset();
			Ext.getCmp("Time").reset();
		},
		failure: function(response)
		{
			Ext.MessageBox.alert('Помилка', 'Неможливо доступитися до бази даних');
		}
	})
	}
	