/*
 * File: app/view/ui/AddAditional.js
 * Date: Tue Sep 06 2011 18:51:33 GMT+0300 (FLE Daylight Time)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

var hash = getUrlVars();
function getUrlVars()
	{
		var vars = [], hash;
		var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
		for(var i = 0; i < hashes.length; i++)
		{
			hash = hashes[i].split('=');
			vars.push(hash[0]);
			vars[hash[0]] = hash[1];
		}
		return vars;
	}
 
 strObjid = hash['objid'];
Ext.define('Borsuko.view.ui.AddAditional', {
    extend: 'Ext.panel.Panel',


    initComponent: function() {
        var me = this;
        me.items = [
            {
                xtype: 'form',
                frame: true,
                height: 389,
                id: 'tabs1',
                bodyPadding: 10,
                animCollapse: false,
                collapsed: false,
                collapsible: true,
                frameHeader: false,
                title: 'Додавання додаткового обладнання',
                items: [
                    {
                        xtype: 'container',
                        border: 0,
                        height: 298,
                        id: 'Container1',
                        padding: 10,
                        width: 661,
                        items: [
                            {
                                xtype: 'textfield',
                                id: 'Model',
                                width: 500,
                                toFrontOnShow: false,
                                name: 'Model',
                                fieldLabel: 'Модель',
                                preventMark: true,
                                emptyText: 'Модель'
                            },
                            {
                                xtype: 'textfield',
                                id: 'vendor',
                                width: 500,
                                name: 'vendor',
                                fieldLabel: 'Виробник',
                                emptyText: 'Виробник'
                            },
                            {
                                xtype: 'textareafield',
                                id: 'description',
                                width: 500,
                                name: 'description',
                                fieldLabel: 'Опис',
                                emptyText: 'Опис'
                            },
                            {
                                xtype: 'combobox',
								editable:false,
                                id: 'Category',
                                width: 500,
                                name: 'Category',
                                fieldLabel: 'Категорія',
                                emptyText: 'Вибір ...',
                                displayField: 'CategoryName',
                                store: 'CategoryStore',
                                valueField: 'CategoryName'
                            },
                            {
                                xtype: 'combobox',
								editable:false,
                                id: 'SubCategory',
                                width: 500,
                                name: 'SubCategory',
                                fieldLabel: 'Субкатегорія',
                                emptyText: 'Вибір ...',
                                displayField: 'SubCategoryName',
                                store: 'SubCategoryStore',
                                valueField: 'SubCategoryName'
                            },
                            {
                                xtype: 'combobox',
								editable:false,
                                id: 'type',
                                width: 500,
                                name: 'type',
                                fieldLabel: 'Тип обладнання',
                                emptyText: 'Вибір ...',
                                displayField: 'type',
                                queryMode: 'local',
                                store: 'TypObladnannia_Store',
                                valueField: 'type'
                            },
                            {
                                xtype: 'textfield',
                                id: 'Price',
                                width: 500,
                                name: 'Price',
                                fieldLabel: 'Ціна',
                                emptyText: 'Ціна'
                            },
                            {
                                xtype: 'combobox',
								editable:false,
                                id: 'Valiuta',
                                width: 500,
								store: 'ValiutaStore',
                                fieldLabel: 'Валюта',
                                emptyText: 'Вибір...',
                                displayField: 'name',
                                queryMode: 'local',
                                valueField: 'abbr'
                            },
                            {
                                xtype: 'combobox',
								editable:false,
                                id: 'OdVym',
                                width: 500,
                                name: 'OdVym',
                                fieldLabel: 'Одиниці виміру',
                                emptyText: 'Вибір...',
                                displayField: 'OdVymiru',
                                store: 'store_OdVymiru',
                                valueField: 'OdVymiru'
                            }
                        ]
                    }
                ],
                dockedItems: [
                    {
                        xtype: 'toolbar',
                        dock: 'top',
                        items: [
                            {
                                xtype: 'button',
                                text: 'Додати додаткове обладнання',
								iconCls: 'add',
								handler : function(){
								   AddFirstRecord();
								}
                            },
                            {
                                xtype: 'button',
                                text: 'Повернутися до перегляду Об`єкту',
								iconCls: 'chart',
								handler : function(){
								strUrl = "/totals.php?objid="+strObjid;
								window.location = strUrl;
								}
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'form',
                frame: true,
                height: 252,
                id: 'tabs2',
                itemId: 'tabs2',
                bodyPadding: 10,
                animCollapse: false,
                collapsed: false,
                collapsible: true,
                frameHeader: false,
                title: 'Інші витрати',
                trackResetOnLoad: true,
                items: [
                    {
                        xtype: 'container',
                        border: 0,
                        height: 298,
                        id: 'Container2',
                        padding: 10,
                        width: 661,
                        items: [
                            {
                                xtype: 'textfield',
                                id: 'Typ',
                                width: 500,
                                toFrontOnShow: false,
                                fieldLabel: 'Витрата',
                                preventMark: true,
                                emptyText: 'Витрата'
                            },
                            {
                                xtype: 'textareafield',
                                id: 'Opys_vytrat',
                                width: 500,
                                fieldLabel: 'Опис Витрати',
                                emptyText: 'Опис'
                            },
                            {
                                xtype: 'combobox',
								editable:false,
                                id: 'type1',
                                width: 500,
                                name: 'type1',
                                fieldLabel: 'Тип витрати',
                                emptyText: 'Вибір ...',
                                displayField: 'type',
                                queryMode: 'local',
                                store: 'TypVytrat',
                                valueField: 'type'
                            },
                            {
                                xtype: 'textfield',
                                id: 'Suma',
                                width: 500,
                                name: 'Suma',
                                fieldLabel: 'Сума в грн.',
                                emptyText: 'Сума'
                            }
                        ]
                    }
                ],
                dockedItems: [
                    {
                        xtype: 'toolbar',
                        dock: 'top',
                        items: [
                            {
                                xtype: 'button',
                                text: 'Додати додаткові витрати',
								iconCls: 'add',
								handler : function(){
								   Add_dodatkovi_vytraty();
								}
                            },
                            {
                                xtype: 'button',
                                text: 'Повернутися до перегляду Об`єкту',
								iconCls: 'chart',
								handler : function(){
									var strObjid = hash['objid'];
									strUrl = "/totals.php?objid="+strObjid;
									window.location = strUrl;
								}
                            }
                        ]
                    }
                ]
            }
        ];
        me.callParent(arguments);
    }
});


function AddFirstRecord(){		
		
			var str_OdVym = Ext.getCmp("OdVym").getValue();
			var str_Category = Ext.getCmp("Category").getValue();
			var str_SubCategory = Ext.getCmp("SubCategory").getValue();
			
			var str_Model = Ext.getCmp("Model").getValue();
			var str_vendor = Ext.getCmp("vendor").getValue();
			var str_description = Ext.getCmp("description").getValue();
			var str_type = Ext.getCmp("type").getValue();
		
			var str_Price = Ext.getCmp("Price").getValue();
			var str_Valiuta = Ext.getCmp("Valiuta").getValue();
			
		if (str_Model == "" || str_vendor =="" || str_description =="" || str_type =="" || str_Price =="" || str_Valiuta =="") {
			Ext.MessageBox.alert('Message', 'Будь-ласка, заповніть всі поля!');
		}
		else
		{
			Ext.getCmp("Model").reset();
			Ext.getCmp("vendor").reset();
			Ext.getCmp("description").reset();
			Ext.getCmp("type").reset();
			Ext.getCmp("Price").reset();
			Ext.getCmp("Valiuta").reset();
			
			
		if (str_type == "активні") 
		{
			var str_type_trans = 'active';
			var strTypeID = 1
		}
		else
		{
			var str_type_trans = 'montazh';
			var strTypeID = 2
			
		}
	Ext.Ajax.request(
	{
		url: './php/insertAditional.php',
		params: {
			Model: str_Model,
			OdVym: str_OdVym,
			Category: str_Category,
			SubCategory: str_SubCategory,
			description: str_description,
			vendor: str_vendor,
			type: str_type,
			type_trans :str_type_trans,
			price: str_Price,
			Valiuta: str_Valiuta,
			TypeID:strTypeID,
			strObjid: strObjid
	},
		success: function()
		{
	
			//this.body.unmask();
			//this.hide();
			Ext.MessageBox.alert('Дані Збережені!', 'Додаткове обладнання додане!');
		},
		failure: function(response)
		{
			Ext.MessageBox.alert('Помилка', 'Неможливо доступитися до бази даних');
		}
	})
	}
	}
	
	
	function Add_dodatkovi_vytraty(){		
			var strObjid = hash['objid'];
			var str_Typ = Ext.getCmp("Typ").getValue();
			var str_Opys_vytrat = Ext.getCmp("Opys_vytrat").getValue();
			var str_Suma = Ext.getCmp("Suma").getValue();
			var str_type = Ext.getCmp("type1").getValue();
			var str_Valiuta = "grivna";
			
			if (str_type == "роботи") {
				var strTypeID = 3
			}
			if (str_type == "інше") {
				var strTypeID = 4
			}
			
	
		if (str_Typ == "" || str_Opys_vytrat =="" || str_Suma =="") {
			Ext.MessageBox.alert('Message', 'Будь-ласка, заповніть всі поля!');
		}
		else
		{
			Ext.getCmp("Typ").reset();
			Ext.getCmp("Opys_vytrat").reset();
			Ext.getCmp("type1").reset();
			Ext.getCmp("Suma").reset();
			
	Ext.Ajax.request(
	{
		url: './php/insertDodatkoviVytraty.php',
		params: {
			Typ: str_Typ,
			TypeID: strTypeID,
			type: str_type,
			Opys_vytrat: str_Opys_vytrat,
			strObjid: strObjid,
			Valiuta: str_Valiuta,
			Suma: str_Suma
			
	},
		success: function()
		{
	
			//this.body.unmask();
			//this.hide();
			Ext.MessageBox.alert('Дані Збережені!', 'Додаткові витрати збережені!');
		},
		failure: function(response)
		{
			Ext.MessageBox.alert('Помилка', 'Неможливо доступитися до бази даних');
		}
		})
	}
	}			