/*
 * File: designer.js
 * Date: Fri Sep 16 2011 15:49:23 GMT+0300 (FLE Daylight Time)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    name: 'Borsuko',

    stores: [
        'ObjThemesStore',
        'PieChartStore',
        'store_users', 
        'vykonavciStore',
        'ObjectStore',
        'KontragentyStore',
        'store_all_kontragenty',
        'TotalObjectStore',
        'DataForNariad',
        'store_pracivnyky',
        'store_postachalniky',
        'PryznachenniaStore',
        'store_OdVymiru',
        'CategoryStore',
        'SubCategoryStore',
        'AllObjectsStore',
        'Active_Store',
        'SkladStore',
        'store_fond',
        'Montazh_Store',
        'OpenObjectsStore',
        'CloseObjectsStore',
        'NariadView_Open',
        'NariadView_All',
        'NariadView_Close',
        'NariadView_Finalized',
        'OpenNarahuvannia_Store',
        'ClosedNarahuvannia_Store',
        'Vyplaty_store',
        'KursStore',
        'StanNariadu',
        'StanObjektu',
        'StanNarahuvannia',
        'TypVytrat',
        'ColumnChartStore',
        'TypKontragenta_store',
        'TypObladnannia_Store',
        'ValiutaStore'
    ],

    launch: function() {
        Ext.QuickTips.init();

        
        var cmp9 = Ext.create('Borsuko.view.totals', {
            renderTo: Ext.getBody()
        });
        cmp9.show();
        
    }
});
